// Generated by CoffeeScript 1.8.0
(function() {
  var Logging, root;

  Logging = (function() {
    function Logging() {}

    Logging.log = function(msg) {
      if (console) {
        return console.log(msg);
      }
    };

    Logging.error = function(msg) {
      if (console) {
        return console.error(msg);
      }
    };

    Logging.warn = function(msg) {
      if (console) {
        return console.warn(msg);
      }
    };

    Logging.info = function(msg, level) {
      var space;
      if (level == null) {
        level = 0;
      }
      space = function(n) {
        var i, s, _i;
        s = '';
        for (i = _i = 0; 0 <= n ? _i < n : _i > n; i = 0 <= n ? ++_i : --_i) {
          s += '  ';
        }
        return s;
      };
      if (console) {
        return console.log((new Date()).toLocaleTimeString(), space(level), msg);
      }
    };

    return Logging;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Logging = Logging;

}).call(this);
