// Generated by CoffeeScript 1.8.0
(function() {
  var Profile, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Profile = (function(_super) {
    __extends(Profile, _super);

    function Profile() {
      return Profile.__super__.constructor.apply(this, arguments);
    }

    Profile.configure("Profile", "name", "type", "scheme", "pac_url", "host", "port", "bypass", "use_auth", "username", "password", "testlink");

    Profile.extend(Spine.Model.Local);

    Profile.getByName = function(name) {
      return this.select(function(profile) {
        return profile.name === name;
      });
    };

    Profile.prototype.toTemplateMapping = function() {
      var k, v, xx, _ref;
      xx = {};
      _ref = this.attributes();
      for (k in _ref) {
        v = _ref[k];
        xx[k] = v;
      }
      return xx;
    };

    return Profile;

  })(Spine.Model);

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Profile = Profile;

}).call(this);
