// Generated by CoffeeScript 1.8.0
(function() {
  var profileTpl, root, tmpls;

  tmpls = {};

  profileTpl = "<li class=\"mochi_list_item profile\" name=\"{{=it.name}}\">\n    <input name=\"profile\" class=\"mochi_radio widget\" type=\"radio\" value=\"{{=it.name}}\"/>\n    <a class=\"value edit\" href=\"\#{{=it.name}}\" title=\"edit\"></a>\n    <label class=\"label\">{{=it.name}}</label>\n    <sup class=\"ping\"></sup><sup class=\"rate\"></sup>\n</li>";

  tmpls['profile'] = doT.template(profileTpl);

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.tmpls = tmpls;

}).call(this);
